[HDU 34] Vista publicaciones
LogiLinkP/LogiLinkP.github.io pull request #287
Opened 2023-10-12 17:29 UTC by marcelo863

Y antes de que lo digan, si, la vista me quedó fea como pegarle a la mamá, el diseño web no es mi pasión precisamente.

Nota: Aceptar también la pull request del backend asociada a la historia 34

Como estudiante:
- Ver en la barra lateral el botón "publicaciones", pulsarlo y acceder a la vista (Probar con distintos estudiantes de distintas carreras)

Como encargado:
- Ver en la barra lateral el botón "publicaciones", pulsarlo y acceder a la vista.
- Pulsar en "agregar publicación", llenar el formulario (Como primera iteración, con la opción de programar publicación en "No")
- Pulsar en "Editar" en una publicación, llenar el formulario (Como primera iteración, con la opción de fijar publicación en la misma opción en la que estaba)
- Pulsar en "Eliminar" en una publicación
- Con ya varias publicaciones creadas, editar la fijación de una publicación para ver cómo cambia de posición.
- Crear una publicación programada: Crear una publicación con la opción de "programar publicación" en si (Preferiblemente la misma fecha pero unos dos minutos adelantado), esperar hasta pasar la fecha programada y recargar la página.

2023-10-13 19:12 UTC, rtallarr commented
No se puede cerrar sesion en la vista publicaciones (tanto encargado como alumno)

2023-10-13 19:14 UTC, rtallarr commented
No se todas las publicaciones
<hr>
![image](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/89488066/03e59a75-46ba-49ba-af64-3d9d60b3367a)
Vista alumno
<hr>
![image](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/89488066/7cc13793-4de2-4120-9491-0a083b0320d2)
vista encargado

2023-10-13 19:15 UTC, rtallarr commented
Si el encargado misclickea en editar no se puede cancelar la edicion

2023-10-13 19:17 UTC, rtallarr commented
Si el encargado elimina la publicacion, se le sigue mostrando al alumno

2023-10-13 19:19 UTC, rtallarr commented
crear una publicacion da internal server error (500)

2023-10-13 19:21 UTC, rtallarr requested changes
ver comentarios

2023-10-21 00:29 UTC, Lirlisa requested changes
- [ ] Al agregar una publicación y luego agregar una nueva, aparecen los textos de la publicación recien hecha.
![imagen](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/42386589/7521b09b-f8dd-4810-afca-b5ebac9dae7d)

- [ ] Al editar una publicación, no sale el texto de fijar publicación
![imagen](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/42386589/820c3957-5e61-48d5-90fb-083c054b80cc)

- [ ] Siguiendo lo anterior, los campos deberían venir pre llenados
- [ ] Faltan mensajes que digan que los campos deben estar llenados, si no lleno algo no pasa nada al presionar el botón publicar.
- [ ] Si escribo menos de 2 caracteres, sale un error en blanco
![imagen](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/42386589/82e43ed5-d229-4990-8577-5e64bc2afe99)

- [ ] No se guarda la hora correctamente al programar publicación
- [ ] Las publicaciones no se generan a la hora adecuada ver comentarios en backend
- [ ] En vista de estudiantes debería salir un mensaje diciendo que no hay publicaciones en vez de mostrar todo vacío
- [ ] ### **¡¡¡¡¡[Usa las tarjetas de la plantilla es copiar y pegar](https://www.youtube.com/watch?v=dQw4w9WgXcQ)!!!!!**

2023-10-23 14:44 UTC, merged